# Introduction to NumPy

**NumPy** is a library written for scientific computing and data analysis. It stands for numerical python.

The most basic object in NumPy is the ```array```, which is **homogenous** in nature. By homogenous, we mean that all the elements in a numpy array have to be of the **same data type**, which is commonly numeric (float or integer). 

### Numpy vs Lists 

In [ ]:
# intialise a list with the following elements: 1, 2, 3, 4, 5


# try to multiply 2.5 directly to the created list



Lists cannot operate over the entire data together. You need to run _map_ or _apply_ functions to multiply each element with 2.5. Let's try to perform this using a NumPy array.

### Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

In [4]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np


In [5]:
# Creating a 1-D array using a list
# np.array() takes in a list or a tuple as argument, and converts into an array

np_l = np.array([1 , 4 , 7])
np_l * 2.5

array([ 2.5, 10. , 17.5])

In [ ]:
# Multiply each element with 2.5 



In [7]:
# Print the result using the print command. Compare the structure of list and array.
print(np_l * 2.5)

[2.5 0.  5. ]


In [11]:
# Create a 1-D array using with the elements (1, abc, True)
np_l = np.array([1 , 0, 2])
np_a = np.array([3 , 4 , 4])

a = np_l + np_a
print(a)


[4 4 6]


In [12]:
np.array( [1.0, 2, 3.5, 0.2, True] )

array([1. , 2. , 3.5, 0.2, 1. ])

You can see above that the elements are of single data type. The numerical and the boolean value is converted to string. 

### Operations over Arrays
One thing to note here is that NumPy comes with its own set of methods and operations. You should not assume that the operators will work in the same way as lists. Look at the example below.

In [ ]:
# Create 2 lists with elements (1, 2, 3) and (4, 5, 6)
list1 = 
list2 = 

# Use the '+' operator and print the results



In [ ]:
# Convert the above lists to arrays and use the '+' operator

np_1 = 
np_2 = 


You can look at the difference between the two outputs. We will look at different operations over NumPy arrays in detail in the coming segments.