# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [3]:
# importing the NumPy library

import numpy as np

In [4]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(1,5)


# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)

In [5]:
# checking the created array: np_1
print(np_1)

[1 2 3 4]


In [6]:
# checking the created array:np_2
print(np_2 )

[0. 0. 0. 0. 0.]


In [7]:
# data type of np_2
np_2.dtype

dtype('float64')

In [8]:
# specifying the data type of the array in the provided attribute
np.zeros(5,dtype = "int")

array([0, 0, 0, 0, 0])

In [9]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [13]:
# check the dimension of the arrays
# array np_1
np_1.size

4

In [14]:
# check the dimension of the arrays
# array np_2
np_2.size

5

In [15]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5)

# checking the created array:np_3
print(np_3)

[1. 1. 1. 1. 1.]


In [16]:
# check the dimension of the arrays
# array np_2
np_2.size

5

In [24]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

[-1. -1. -1. -1. -1.]


In [28]:
# creating an array of fixed length
np_4 = np.linspace(1,10,5)

# checking the created array:np_4
print(np_4)

[ 1.    3.25  5.5   7.75 10.  ]


In [29]:
# checking the created array:np_1
np_1

array([1, 2, 3, 4])

In [30]:
# squaring the terms of np_1
np.power(np_1 , 2)

array([ 1,  4,  9, 16])

In [31]:
# getting the absolute value of the elements
np.absolute(np.array([-1,1,2,-5]))

array([1, 1, 2, 5])

In [ ]:
# np.sin()
# np.cos()

In [ ]:
# np.log()

### Empty arrays

In [32]:
# Creating empty arrays

x = np.arange(1, 6)
y = np.empty(5)

# filling the empty array
np.multiply(x , 10 , out = y)

array([10., 20., 30., 40., 50.])

In [33]:
# printing the output obtained above
y

array([10., 20., 30., 40., 50.])

### Aggregation of array elements

In [35]:
# Reducing the elements to a single value based on addition
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [36]:
np.add.reduce(x)

15

In [38]:
# Cummulative addition of elements at each element
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [ ]:
np.linalg

In [39]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    ``numpy.linalg``
    
    The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
    low level implementations of standard linear algebra algorithms. Those
    libraries may be provided by NumPy itself using C versions of a subset of their
    reference implementations but, when possible, highly optimized libraries that
    take advantage of specialized processor functionality are preferred. Examples
    of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
    are multithreaded and processor dependent, environmental variables and external
    packages such as threadpoolctl may be needed to control the number of threads
    or specify the processor architecture.
    
    - OpenBLAS: https://www.openblas.net/
    - threadpoolctl: https://github.com/joblib/threadpoolctl
    
    Please note that the most-used linear algebra functions in NumPy are present in
    t

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [41]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [42]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [43]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))


array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [44]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.76031781, 0.30990155, 0.59520274, 0.39390184],
       [0.34789639, 0.0263208 , 0.46270431, 0.13605894],
       [0.51401261, 0.17503821, 0.12806874, 0.63811872]])

In [47]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[9, 5, 9, 8],
       [0, 2, 6, 4],
       [0, 4, 6, 8],
       [9, 0, 1, 8]])